"""new fields in user model

Revision ID: b13ec7ab2cd8
Revises: bd91929cd097
Create Date: 2018-03-19 13:15:22.987930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13ec7ab2cd8'
down_revision = 'bd91929cd097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_id')
    # ### end Alembic commands ###
